-- 30 lokali z 5 przewodnikow kuchennych batch 2 (Pierogi/Polish, Thai, Mexican,
-- Kebab/Middle Eastern, Korean). Hankki juz jest w bazie (on conflict pomija).
-- Odpal w SQL Editorze, potem sync /api/refresh-places.

insert into venues (slug, name, district, address, price_range, tags, hours_short, description_en) values
  -- Pierogi / Polish
  ('u-stasi',              'Jadłodajnia U Stasi',       'Stare Miasto', 'ul. Mikołajska 16, 31-027 Kraków',        '$',   '{"polish","pierogi","lunch only"}',            'Weekday lunch ~12-17, sells out', 'A family canteen running for roughly eighty years, the local consensus for the best pierogi in Krakow. Weekday lunch only, queue before noon.'),
  ('przystanek-pierogarnia','Przystanek Pierogarnia',   'Wesoła',       'ul. Bonerowska 14, 31-030 Kraków',        '$',   '{"polish","pierogi","hand-folded"}',           'Mon-Fri 11-20, Sat 11-17',        'A small pierogi room with an open kitchen where the dough is rolled and folded by hand in view of guests.'),
  ('mr-vincent',           'Pierogi Mr Vincent',        'Kazimierz',    'ul. Bożego Ciała 12, 31-059 Kraków',      '$',   '{"polish","pierogi","30 fillings"}',           'Daily 11-21',                     'A tiny Van Gogh-themed pierogi room in Kazimierz with a menu of about thirty fillings, open evenings.'),
  ('pod-temida',           'Bar mleczny Pod Temidą',    'Stare Miasto', 'ul. Grodzka 43, 31-001 Kraków',           '$',   '{"polish","milk bar","budget"}',               'Daily 9 to ~20',                  'A surviving communist-era milk bar on the Royal Route with most mains under twenty zloty.'),
  ('pod-baranem',          'Restauracja Pod Baranem',   'Stare Miasto', 'ul. św. Gertrudy 21, 31-049 Kraków',      '$$',  '{"polish","classic","white tablecloth"}',      'Lunch and dinner daily',          'Family-run since 1997 by chef-owner Jan Baran, the white-tablecloth standard for old-school Polish cooking near Wawel.'),
  ('bottiglieria-1881',    'Bottiglieria 1881',         'Kazimierz',    'ul. Bocheńska 5, 31-061 Kraków',          '$$$', '{"modern polish","two michelin stars","tasting menu"}', 'Dinner seatings, book ahead', 'Two Michelin stars in the 2026 guide, the first double in Poland. Refined modern Polish tasting menus in an 1881 wine warehouse.'),
  -- Thai
  ('molam',                'Molám Thai Canteen & Bar',  'Piasek',       'ul. Rajska 3/4, 31-124 Kraków',           '$$',  '{"thai","bib gourmand","open fire"}',          'Lunch and dinner, book ahead',    'Michelin Bib Gourmand since 2023, the first for a Thai restaurant in Poland. Open-fire cooking from a Bangkok and London trained founder.'),
  ('taj-thai',             'Taj Kraków',                'Kazimierz',    'ul. Miodowa 19, 31-055 Kraków',           '$$',  '{"thai","all-thai kitchen","vegan options"}',  'Daily from 12',                   'An entirely Thai kitchen, head chef included, on Miodowa in Kazimierz, with a second branch on Szpitalna.'),
  ('luktung',              'Luktung',                   'Podgórze',     'Rynek Podgórski 11, 30-518 Kraków',       '$$',  '{"thai","southeast asian","sharing plates"}',  'Dinner oriented',                 'The second venue from the Molám founder, Southeast Asian sharing plates on the Podgorze square with a monthly-changing menu.'),
  ('thai-fun',             'Thai Fun',                  'Czyżyny',      'ul. Centralna 51aa, 31-586 Kraków',       '$',   '{"thai","family-run","neighborhood"}',         'Tue-Sun 12-19:30',                'A family-run neighborhood Thai kitchen in Czyżyny holding 4.8 stars across more than a thousand reviews.'),
  ('little-thai',          'Little Thai',               'Podgórze Duchackie', 'ul. Macedońska 6, 30-427 Kraków',   '$',   '{"thai","takeaway","weekend only"}',           'Thu-Sun to 19:30',                'A takeaway-first Thai counter open four days a week and rated 4.9, among the highest of any Thai kitchen in the city.'),
  ('samui',                'Samui',                     'Stare Miasto', 'ul. Wiślna 10, 31-007 Kraków',            '$$',  '{"thai","central","first thai in krakow"}',    'Daily 12-22',                     'Krakow''s first Thai restaurant with a head chef from Thailand, two minutes off the Main Square.'),
  -- Mexican
  ('tacoteka',             'Tacoteka',                  'Podgórze',     'ul. Kalwaryjska 75, 30-504 Kraków',       '$$',  '{"mexican","tacos","family-run"}',             'Daily 12-21',                     'Run by a Mexican family with Yucatán roots, the most authentic tacos and birria in the city.'),
  ('del-jero',             'Del Jero Mexican Street Food','Zabłocie',   'ul. Lipowa 4D, 30-702 Kraków',            '$',   '{"mexican","birria","street food"}',           'Mon-Sat 12-21, Sun from 12:30',   'The birria specialist near the Schindler museum block, around 4.8 from a thousand reviews.'),
  ('mexican-food-kleparz', 'Mexican Food',              'Kleparz',      'Plac Targowy Nowy Kleparz 18, 31-131 Kraków', '$', '{"mexican","tortas","market stall"}',        'Daily 11-22',                     'A Nowy Kleparz market stall with a native Mexican owner, house-made tortillas and one of the only torta menus in Krakow.'),
  ('manzana',              'Manzana 3.0',               'Kazimierz',    'ul. Kupa 6, 31-057 Kraków',               '$$$', '{"mexican","tex-mex","margaritas"}',           'Daily, lunch and dinner',         'The third incarnation of a Kazimierz institution, with the largest tequila range in Krakow and the margaritas locals cite as best.'),
  ('puente',               'Puente',                    'Kazimierz',    'Plac Nowy 3, 31-056 Kraków',              '$$',  '{"mexican","imported chiles","live music"}',   'Weekdays from 17, weekends from 12', 'A Plac Nowy kitchen cooking with imported Mexican chiles, everything made on site, weekday lunch sets under forty zloty.'),
  ('los-gorditos',         'Los Gorditos',              'Kazimierz',    'ul. Augustiańska 24, 31-064 Kraków',      '$$',  '{"mexican","tex-mex","counter service"}',      'Sun-Thu 12-21, Fri-Sat to 22',    'Counter-service Tex-Mex frying its own tortilla chips and making salsas in-house.'),
  -- Kebab / Middle Eastern
  ('jamra',                'Jamra',                     'Zabłocie',     'ul. Zabłocie 25A, 30-701 Kraków',         '$',   '{"syrian","kebab","halal","charcoal grill"}',  'Daily ~11-24',                    'Syrian-run halal charcoal grill whose Aleppo wrap with house garlic paste keeps being named the best kebab in Krakow.'),
  ('kebab-soltan',         'Kebab Soltan',              'Kleparz',      'ul. Warszawska 14, 31-155 Kraków',        '$',   '{"kebab","halal","open late"}',                'Daily to 24, Fri-Sat to ~2',      'Around 4.8 stars across more than 2,300 reviews, the biggest top-rated kebab in the city, open late on weekends.'),
  ('tandoor-kebab',        'Tandoor Kebab',             'Kazimierz',    'ul. Starowiślna 97, 31-052 Kraków',       '$',   '{"kebab","halal","tandoor bread"}',            'Lunch and dinner daily',          'Opened autumn 2025 and bakes each flatbread to order in a real tandoor, reportedly the first kebab in Krakow to do so.'),
  ('arabia-kebab',         'Arabia Kebab',              'Kleparz',      'Rynek Kleparski 5, 31-150 Kraków',        '$',   '{"syrian","shawarma","market"}',               'Lunch and dinner',                'The food-blogger counterpick for best kebab, a Stary Kleparz stall where first-timers get sweet tea and baklava on the house.'),
  ('hamsa',                'Hamsa',                     'Kazimierz',    'ul. Szeroka 2, 31-053 Kraków',            '$$',  '{"israeli","mezze","vegan range"}',            'Daily, weekend breakfast from 9', 'Israeli mezze on the Szeroka square since 2012, with hummus with slow-cooked beef and a wide vegan range.'),
  ('amamamusi',            'Hummus Amamamusi',          'Kazimierz',    'ul. Meiselsa 4, 31-058 Kraków',           '$',   '{"hummus","vegetarian","fresh daily"}',        'Mon-Fri 9-20, Sat 12-20',         'A fully vegetarian hummus specialist with about twenty-five varieties made fresh on site every morning.'),
  ('mazaya',               'Mazaya',                    'Piasek',       'ul. Krupnicza 22, 31-123 Kraków',         '$',   '{"syrian","falafel","breakfast"}',             'Daily 11-22, Krupnicza from 8',   'The Syrian falafel kitchen grown to four Krakow locations, with a Levantine breakfast from eight on Krupnicza.'),
  -- Korean
  ('mu-krakow',            'MU Restaurant',             'Zabłocie',     'ul. Przemysłowa 15, 30-701 Kraków',       '$$',  '{"korean","from seoul","bibimbap"}',           'Daily 11-22',                     'Opened late 2025 by the owners of Seoul cafe Mudaeruk, with a Korean chef, in a post-industrial hall by MOCAK.'),
  ('dangol',               'Dangol',                    'Kazimierz',    'ul. Józefa Dietla 55/1, 31-050 Kraków',   '$$',  '{"korean","hot pot","korean market"}',         'Lunch and dinner to 21',          'A basement Korean dining room under the owners'' own grocery, with shared K-hot pots and semi-private rooms for groups.'),
  ('oriental-spoon',       'Oriental Spoon',            'Kleparz',      'ul. Ignacego Paderewskiego 4, 31-118 Kraków', '$', '{"korean","bibimbap","since 2013"}',         'Lunch and early dinner to 20',    'Krakow''s Korean stalwart since around 2013, chef Park''s tiny menu built around bibimbap with gochujang-honey sauce.'),
  ('pan-kimbap',           'Pan KimBap',                'Podgórze',     'ul. Kalwaryjska 17, 30-509 Kraków',       '$',   '{"korean","kimbap","vegan options"}',          'Lunch and early dinner to 20',    'The highest-rated Korean spot in the city, 4.8 from about 1,600 reviews, kimbap rolls and twenty-zloty mains.'),
  ('chois',                'Choi''s Korean Chicken & Cupbop', 'Stare Miasto', 'ul. Krupnicza 6, 31-123 Kraków',   '$',   '{"korean","fried chicken","counter"}',         'Daily 11-22',                     'Krakow''s dedicated Korean fried chicken address, frying to order in the historic Elefant building by the Bagatela theatre.')
on conflict (slug) do nothing;

-- Mapowania artykul -> lokal
insert into article_venues (article_slug, venue_id, position)
select a.slug_art, v.id, a.pos
from (values
  ('pierogi-krakow','u-stasi',1),('pierogi-krakow','przystanek-pierogarnia',2),('pierogi-krakow','mr-vincent',3),('pierogi-krakow','pod-temida',4),('pierogi-krakow','pod-baranem',5),('pierogi-krakow','bottiglieria-1881',6),
  ('thai-krakow','molam',1),('thai-krakow','taj-thai',2),('thai-krakow','luktung',3),('thai-krakow','thai-fun',4),('thai-krakow','little-thai',5),('thai-krakow','samui',6),
  ('mexican-krakow','tacoteka',1),('mexican-krakow','del-jero',2),('mexican-krakow','mexican-food-kleparz',3),('mexican-krakow','manzana',4),('mexican-krakow','puente',5),('mexican-krakow','los-gorditos',6),
  ('kebab-krakow','jamra',1),('kebab-krakow','kebab-soltan',2),('kebab-krakow','tandoor-kebab',3),('kebab-krakow','arabia-kebab',4),('kebab-krakow','hamsa',5),('kebab-krakow','amamamusi',6),('kebab-krakow','mazaya',7),
  ('korean-krakow','hankki',1),('korean-krakow','mu-krakow',2),('korean-krakow','dangol',3),('korean-krakow','oriental-spoon',4),('korean-krakow','pan-kimbap',5),('korean-krakow','chois',6)
) as a(slug_art, slug_venue, pos)
join venues v on v.slug = a.slug_venue
on conflict do nothing;
